name: number_picker_example
description: Example app for number_picker package
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  number_picker:
    path: ../
