name: infinite_number_picker
description: A customizable number picker widget with infinite scroll, step values, and styled UI.
version: 1.0.0
homepage: https://github.com/Ayushkayastha/number_picker

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  infinite_listview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
